"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Check, GraduationCap, MapPin, Phone, Sparkles, Trophy, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/components/site/language-context";

const updates = [
  { date: "15 JUL", type: "Admissions", title: "Admissions open for the 2026–27 academic year" },
  { date: "10 JUL", type: "Campus", title: "Annual Day: an evening of creativity and confidence" },
  { date: "28 JUN", type: "Learning", title: "New computer lab expands practical digital learning" },
];

export default function HomePage() {
  const { t } = useLanguage();
  return <>
    <section className="relative min-h-[720px] overflow-hidden bg-[#0b2160] text-white">
      <Image src="/images/virat-learning.jpg" alt="Students collaborating in a science classroom" fill priority sizes="100vw" className="object-cover object-[62%_center] opacity-70" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#071847] via-[#0b2160]/90 to-[#0b2160]/10" />
      <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-[#071847] to-transparent" />
      <div className="container relative mx-auto flex min-h-[720px] max-w-7xl items-center px-4 py-24">
        <div className="max-w-3xl">
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] backdrop-blur-xl"><GraduationCap className="size-4 text-sky-300" /> RBSE affiliated · Viratnagar</div>
          <h1 className="text-5xl font-black leading-[.96] tracking-[-.055em] text-white sm:text-6xl lg:text-[5.6rem]">Every child deserves a place to <span className="text-sky-300">thrive.</span></h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-white/80">{t.home.heroSubtitle}</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-13 rounded-full bg-blue-600 px-7 hover:bg-blue-500"><Link href="/admissions/apply">Apply for admission <ArrowRight className="ml-2 size-4" /></Link></Button><Button asChild size="lg" variant="outline" className="h-13 rounded-full border-white/40 bg-white/10 px-7 text-white backdrop-blur hover:bg-white hover:text-blue-950"><Link href="/contact-us">Book a campus visit</Link></Button></div>
        </div>
      </div>
    </section>

    <section className="relative z-10 -mt-16 px-4"><div className="container mx-auto grid max-w-7xl overflow-hidden rounded-3xl border border-white/70 bg-white/90 shadow-[0_24px_80px_rgba(15,42,114,.18)] backdrop-blur-xl md:grid-cols-3">
      {[{icon:Phone,label:"Speak with admissions",value:"+91 96364 52501",href:"tel:+919636452501"},{icon:CalendarDays,label:"Admissions",value:"Open for 2026–27",href:"/admissions/apply"},{icon:MapPin,label:"Visit us",value:"Viratnagar, Rajasthan",href:"/contact-us"}].map((x,i)=><Link key={x.label} href={x.href} className={`group flex items-center gap-4 p-6 transition hover:bg-sky-50 ${i<2?'md:border-r md:border-blue-100':''}`}><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-blue-700"><x.icon className="size-5" /></span><span><small className="block text-xs font-bold uppercase tracking-wider text-slate-500">{x.label}</small><strong className="mt-1 block text-blue-950">{x.value}</strong></span><ArrowRight className="ml-auto size-4 text-blue-400 transition group-hover:translate-x-1" /></Link>)}</div></section>

    <section className="py-24 md:py-32"><div className="container mx-auto max-w-7xl px-4"><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow">Why families choose Virat</p><h2 className="mt-5 text-4xl font-black leading-tight md:text-6xl">Strong foundations.<br />Limitless possibility.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">A caring school community where excellent teaching, modern learning and enduring values help every student find their strengths.</p><Link href="/about-us" className="mt-8 inline-flex items-center gap-2 font-bold text-blue-700">Discover our approach <ArrowRight className="size-4" /></Link></div><div className="grid gap-4 sm:grid-cols-2">{t.home.features.map((f,i)=>{const icons=[Users,BookOpen,Sparkles];const Icon=icons[i];return <article key={f.title} className={`premium-card p-7 ${i===2?'sm:col-span-2':''}`}><span className="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-sky-400 text-white"><Icon className="size-5" /></span><h3 className="mt-7 text-xl font-extrabold">{f.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{f.body}</p></article>})}</div></div></div></section>

    <section className="overflow-hidden bg-blue-950 text-white"><div className="container mx-auto grid max-w-7xl lg:grid-cols-2"><div className="p-8 md:p-16"><p className="eyebrow !text-sky-300">Learning at every stage</p><h2 className="mt-5 text-4xl font-black text-white md:text-6xl">A clear path from curiosity to confidence.</h2><p className="mt-6 leading-7 text-white/70">Age-appropriate learning that builds skills progressively—supported by attentive teachers and purposeful assessment.</p><div className="mt-10 space-y-3">{["Primary · Classes I–V","Middle · Classes VI–VIII","Secondary · Classes IX–X","Senior Secondary · Classes XI–XII"].map((x,i)=><Link href="/academics/classes" key={x} className="group flex items-center justify-between border-b border-white/15 py-4 font-bold"><span><small className="mr-4 text-sky-300">0{i+1}</small>{x}</span><ArrowRight className="size-4 transition group-hover:translate-x-1" /></Link>)}</div></div><div className="relative min-h-[460px] bg-gradient-to-br from-blue-600 to-sky-400 p-8 md:p-16"><Trophy className="size-10 text-white/80" /><p className="mt-20 text-7xl font-black tracking-[-.07em] text-white md:text-8xl">98.20%</p><h3 className="mt-3 text-2xl font-black text-white">Rohit Yadav</h3><p className="mt-1 font-bold text-blue-950">District Topper · RBSE 2025–26</p><div className="absolute -bottom-20 -right-20 size-72 rounded-full border-[40px] border-white/10" /></div></div></section>

    <section className="py-24 md:py-32"><div className="container mx-auto max-w-7xl px-4"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Achievement, earned</p><h2 className="mt-5 text-4xl font-black md:text-6xl">Our RBSE toppers</h2></div><p className="max-w-lg text-slate-600">Celebrating hard work, dedicated teaching and the support of every family.</p></div><div className="mt-12 grid grid-cols-2 gap-3 lg:grid-cols-5">{t.home.toppers.map((x,i)=><article key={x.name} className={`rounded-2xl p-6 ${i===0?'bg-blue-700 text-white shadow-xl shadow-blue-700/20':'border border-blue-100 bg-white'}`}><span className={`text-xs font-black uppercase tracking-wider ${i===0?'text-sky-200':'text-blue-600'}`}>Rank {x.position}</span><p className={`mt-8 text-3xl font-black ${i===0?'text-white':'text-blue-950'}`}>{x.percent}</p><p className="mt-3 text-sm font-bold">{x.name}</p><p className={`text-xs ${i===0?'text-white/60':'text-slate-500'}`}>{x.subject}</p></article>)}</div></div></section>

    <section className="bg-sky-50 py-24 md:py-32"><div className="container mx-auto max-w-7xl px-4"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">From our campus</p><h2 className="mt-5 text-4xl font-black md:text-5xl">News that keeps you connected.</h2><Button asChild variant="outline" className="mt-8 rounded-full border-blue-200 bg-white"><Link href="/news-events">View all updates</Link></Button></div><div className="divide-y divide-blue-200 border-y border-blue-200">{updates.map(x=><Link href="/news-events/announcements" key={x.title} className="group grid gap-4 py-7 sm:grid-cols-[75px_1fr_auto] sm:items-center"><span className="text-xs font-black tracking-wider text-blue-600">{x.date}</span><span><small className="text-xs font-bold uppercase tracking-wider text-slate-500">{x.type}</small><strong className="mt-1 block text-lg text-blue-950">{x.title}</strong></span><ArrowRight className="size-5 text-blue-500 transition group-hover:translate-x-1" /></Link>)}</div></div></div></section>

    <section className="px-4 py-20"><div className="container mx-auto max-w-7xl overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-blue-700 to-sky-500 p-8 text-center text-white shadow-2xl shadow-blue-700/20 md:p-16"><Check className="mx-auto size-8"/><h2 className="mx-auto mt-6 max-w-3xl text-4xl font-black text-white md:text-6xl">Your child’s next chapter can start here.</h2><p className="mx-auto mt-5 max-w-xl text-white/80">Our admissions team is ready to answer your questions and guide you through every step.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg" className="rounded-full bg-white text-blue-800 hover:bg-sky-50"><Link href="/admissions/apply">Start an application</Link></Button><Button asChild size="lg" variant="outline" className="rounded-full border-white/50 bg-transparent text-white hover:bg-white hover:text-blue-800"><Link href="/contact-us">Talk to our team</Link></Button></div></div></section>
  </>;
}
